openapi: 3.0.0
info:
  title: Hello World
  version: 1.0.0
servers:
  '- url': /v1
paths:
  /users:
    post:
      tags:
        - user
      summary: Post User
      requestBody:
        description: Send user data
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mobileNumber
              properties:
                mobileNumber:
                  type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
components: {}
tags: []
