openapi: 3.0.0
info:
  title: Hello World
  version: 1.0.0
servers:
  - url: /v1
paths:
  /users:
    post:
      tags:
        - user
      summary: Post User
      requestBody:
        description: Send user data
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mobileNumber
              properties:
                mobileNumber:
                  type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /users/all:
    get:
      tags:
        - user
      summary: Get All User
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: 2
                    uuid: 6fc83c8d-bd61-4aeb-8646-132ff0e8502d
                    nama: valent
                    pin: null
                    city: jakarta
                    dob: '19970221'
                    mobile_number: '085360867734'
                    created_at: '2022-03-19T04:04:18.000Z'
                    updated_at: '2022-03-19T05:18:50.000Z'
                    deleted_at: null
                  - id: 3
                    uuid: e9558b4b-5c65-4733-be19-1a4749094475
                    nama: null
                    pin: null
                    city: null
                    dob: null
                    mobile_number: string
                    created_at: '2022-03-27T04:21:07.000Z'
                    updated_at: '2022-03-27T04:21:07.000Z'
                    deleted_at: null
                  - id: 4
                    uuid: 97ac8450-0ef1-4f49-b118-f5be79f13df1
                    nama: null
                    pin: null
                    city: null
                    dob: null
                    mobile_number: '121213'
                    created_at: '2022-03-27T04:22:22.000Z'
                    updated_at: '2022-03-27T04:22:22.000Z'
                    deleted_at: null
components: {}
tags: []
